### ISSUE TITLE
Composer autoloading

### ISSUE THREAD

**Issue by aksalj** [AfricasTalkingLtd/africastalking-php#1] opened 2017-08-17 06:28 UTC
Composer autoloading does not seem to be working:

```shell
composer require africastalking/africastalking
```
Then
```php
<?php
require 'vendor/autoload.php';

$gateway = new AfricasTalkingGateway($USERNAME, $API_KEY);
```
Throws

`Class 'AfricasTalkingGateway' not found in index.php`

Or am I doing something wrong?

**Comment by skedone** [comment] 2017-12-21 16:20
Hi @aksalj, you are not doing anything wrong.
The problem is the library which has never been ported correctly to be used with an autoloader.

I have create a pull request for this #2 
Cheers.

**Comment by ianjuma** [comment] 2018-01-11 19:25
Merged, sorry about the delay!
I will proceed an close this.

**Closed by ianjuma** 2018-01-11 19:25 UTC
